[workspace]
channels = ["conda-forge","bioconda"]
name = "river-slurm"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "==3.11"

[pypi-dependencies]
ansible = ">=6.7.0"
passlib = "==1.7.4"
molecule = ">=6.0.0"
molecule-docker = ">=2.1.0"
docker = ">=7.0.0"
